# The sequence of the pipeline
stages:
  - deploy

# Used to determine which project & env will be used during build & deploy
variables:
  NODE_ENV: "production"
  GCLOUD_ENV: ""
  GCLOUD_PROJECT: "$GCLOUD_PROJECT"
  GCLOUD_ACCOUNT: "$GCLOUD_ACCOUNT"

# Deploy to Google Cloud
deploy:
  image: google/cloud-sdk:alpine
  stage: deploy
  before_script:
    - echo "$GCLOUD_ACCOUNT"
#    - echo "$GCLOUD_ACCOUNT" | base64 -d > /tmp/gcloud-account.json
    - echo "$GCLOUD_ACCOUNT" > /tmp/gcloud-account.json
    - cat /tmp/gcloud-account.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud$GCLOUD_ENV-account.json
    - gcloud auth configure-docker
    - echo "$PROJECT_ID"
    - gcloud config set project $GCLOUD_PROJECT
  script:
    - gcloud config set app/cloud_build_timeout 2700
    - gcloud config set builds/use_kaniko True
    # Cloud Run
    - gcloud builds submit --config cloud-build.yaml
